title: Patricia Nunez
email: patricia.padillanunez@gmail.com
phone: (512)638-6889
description: "Jr. Front End Web Developer For Hire. HTML, CSS, JavaScript, Jekyll, Responsive Web Development, Bootstrap, Wordpress. Austin, Tx."
keywords: "HTML,CSS,JavaScript,Jekyll,Responsive Design,Web Development,Front End Web Developer"

baseurl: ""
url: "https://papanucita.github.io"
twitter_username: papanucita
github_username:  papanucita

# Build settings
permalink: pretty
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

